baseURL: 'https://blog.pieromamberti.com/'
languageCode: en
title: Piero's Blog
theme: anatole
summarylength: 5
enableEmoji: true
enableRobotsTXT: true

params:
  title: Hi ğŸ™‹â€â™‚ï¸I'm Piero 
  author: Piero Mamberti
  description: ğŸ‡®ğŸ‡¹ in London ğŸ‡¬ğŸ‡§ I love ğŸ“š, ğŸ½ and ğŸ’¬ I work with computers ğŸ§‘â€ğŸ’» Continuous learning is my mantra ğŸ§˜ğŸ»â€â™‚ï¸
  profilePicture: images/profile_pic.jpeg
  socialIcons:
    - icon: fab fa-github
      title: Github
      url: https://www.github.com/pmamberti
    - icon: fab fa-twitter
      title: Twitter
      url: https://www.twitter.com/pmamberti
    - icon: fab fa-linkedin
      title: Linkedin
      url: https://www.linkedin.com/in/pmamberti
    - icon: fas fa-envelope
      title: email
      url: mailto:piero.mamberti@gmail.com


menu:
  main:
    - name: Home
      identifier: home
      weight: 100
      url: /
    - name: Posts
      weight: 200
      identifier: posts
      url: /posts/
    - name: About
      weight: 300
      identifier: about
      url: /about/
    - name: CV
      weight: 400
      identifier: cv
      url: /about/cd.md
