baseURL: 'https://blog.pieromamberti.com/'
languageCode: en-us
title: Piero's Blog
theme: anatole

params:
  title: Hi ğŸ™‹â€â™‚ï¸I'm Piero 
  author: Piero Mamberti
  description: I happen to work as an IT Engineer ğŸ§‘â€ğŸ’», but nothing serious ğŸ˜…
  profilePicture: images/profile_pic.jpg
  socialIcons:
    - icon: fab fa-github
      title: Github
      url: https://www.github.com/pmamberti
    - icon: fab fa-twitter
      title: Twitter
      url: https://www.twitter.com/pmamberti
    - icon: fab fa-linkedin
      title: Linkedin
      url: https://www.linkedin.com/in/pmamberti


# menu:
#   main:
#     - name: Home
#       identifier: home
#       weight: 100
#       url: /
#     - name: Posts
#       weight: 200
#       identifier: posts
#       url: /post/
#     - name: About
#       weight: 300
#       identifier: about
#       url: /about/
