baseURL: 'https://blog.pieromamberti.com/'
languageCode: en
title: Piero's Blog
theme: anatole
summarylength: 5
enableEmoji: true
enableRobotsTXT: true

params:
  title: Hi ğŸ™‹â€â™‚ï¸I'm Piero 
  author: Piero Mamberti
  description: I'm from Italy but I live in London. ğŸ‡®ğŸ‡¹ ğŸ‡¬ğŸ‡§ I happen to work as an IT Engineer ğŸ§‘â€ğŸ’» But I promise nothing serious ğŸ˜…
  profilePicture: images/profile_pic.jpeg
  socialIcons:
    - icon: fab fa-github
      title: Github
      url: https://www.github.com/pmamberti
    - icon: fab fa-twitter
      title: Twitter
      url: https://www.twitter.com/pmamberti
    - icon: fab fa-linkedin
      title: Linkedin
      url: https://www.linkedin.com/in/pmamberti
    - icon: fas fa-envelope
      title: email
      url: mailto:piero.mamberti@gmail.com


menu:
  main:
    - name: Home
      identifier: home
      weight: 100
      url: /
    - name: Posts
      weight: 200
      identifier: posts
      url: /posts/
#     - name: About
#       weight: 300
#       identifier: about
#       url: /about/
